<?php

/**
 * @file
 * Drupal's main configuration file.
 *
 * To customize the configuration:
 * - Create a settings.local.php
 * - Edit the templates at .the-build/drupal/settings.*.php
 * - Avoid editing this file
 *
 * @see https://api.drupal.org/api/drupal/sites%21default%21default.settings.php/8.6.x
 */


// This is the core set of defaults from default.settings.php. They will be overridden
// as necessary by the includes below.
$config_directories = [];
$settings['hash_salt'] = '';
$settings['update_free_access'] = FALSE;
$settings['container_yamls'][] = $app_root . '/' . $site_path . '/services.yml';
$settings['file_scan_ignore_directories'] = [
  'node_modules',
  'bower_components',
];
$settings['entity_update_batch_size'] = 50;


// Disable our three default config_split configurations. These will be enabled in the
// settings.build.php file that is compiled for either development or for the artifact.
$config['config_split.config_split.production']['status'] = FALSE;
$config['config_split.config_split.staging']['status'] = FALSE;
$config['config_split.config_split.development']['status'] = FALSE;


// Additional settings files to load. Order is significant.
$settings_filenames = [
  // Host-specific settings.
  'settings.other.php',
  // Settings file generated by palantirnet/the-build
  'settings.build.php',
  // Local settings file for use on individual developer environments
  'settings.local.php',
];

// Load each settings file that is present, in the order specified above.
foreach ($settings_filenames as $settings_filename) {
  $settings_file = "{$app_root}/{$site_path}/{$settings_filename}";
  if (file_exists($settings_file)) {
    include $settings_file;
  }
}
